name: Deploy with staging RPC

on:
  workflow_dispatch:
    inputs:
      subqlAccessToken:
        description: 'Subquery access token https://doc.subquery.network/publish/ipfs/#prepare-your-subql-access-token'
        required: true
        type: string

jobs:
  publish:
    name: IPFS publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use node version 14
        uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org
          cache: 'yarn'

      - name: Install dependencies
        run: yarn
      
      - name: Generate schema type
        run: yarn codegen

      - name: Publish to IPFS
        run: yarn ipfs:publish
        env:
          SUBQL_ACCESS_TOKEN: ${{ github.event.inputs.subqlAccessToken }}
